version: '3'

services:
  # MariaDB container
  mariadb:
    image: yobasystems/alpine-mariadb:latest
    container_name: mariadb
    command: --skip-grant-tables --user=root
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: cinema
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  # PHPMyAdmin container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ''
    ports:
      - "8080:80"
  webserver-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: apache-php
    volumes:
      - ./slim-master/:/var/www/html
    restart: always
    depends_on:
      - mariadb
    ports:
      - "80:80"

volumes:
  mysql_data:
